= Spring Tracing with Zipkin Brave and Spring Cloud Sleuth
Mario Gray <mgray@pivotal.io>
:Author Initials: MVG
:toc:
:icons:
:numbered:
:website: https://cloud.spring.io/spring-cloud-sleuth/

== Motivation
What is:
Trace data is composed of a parent:child tree structure called a Directed Acyclic Graph
(DAG for short).  Where a root node represents the `trace` or overall journey, and each
`span` represents an individual hop along the service route. Our application will 
demonstrate this kind of relationship:

    client -> </frontent> -> </backend> -> </backend2>
	  			AAA 		   AAA:BBB		 BBB:CCC
				  \
				    BBB
					 \
				       CCC
 
== Starting up the app
To start, setup a new spring app with the dependencies for Web, Lombok.
Hit this http://start.spring.io/starter.zip?dependencies=web,lombok,h2,jpa&type=maven-project&javaVersion=1.8&baseDir=spring-tracing&packageName=mcp.client&name=spring-tracing[preconfigured start.spring.io] link
to download the base project. Find your favorite editor, and start with standing up a REST 
controller.

.TracingApplication
[source,java]
----
@SpringBootApplication
public class TracingApplication {
	public static void main(String[] args) {
		SpringApplication.run(TracingApplication.class, args);
	}
}

@Configuration
class TracingConfiguration {
	@Bean
	RestTemplate restTemplate() {
		return new RestTemplate(); 
	}
}

@RestController
class TracingRestController {
	private final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(TracingRestController.class);
	private final RestTemplate restTemplate;

	public TracingRestController(RestTemplate rt) {
		this.restTemplate = rt;
	}

	@GetMapping("/backend")
	public String deviceNames(HttpServletRequest req) {
		String clientId = req.getHeader("client-id");
		log.info("clientId=" + clientId);
		return "Hello, " + clientId;
	}

	@GetMapping("/frontend")
	public String callBackend() {
		return restTemplate.getForObject("http://localhost:8080/backend", String.class);
	}
}
----

Then setup the logging properties:

.application.properties
[source,script]
----
logging.pattern.level=%d{ABSOLUTE} [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n
logging.level.root=off
logging.level.mcp.cloudtrace=info
spring.application.name=spring-tracing
----

Startup the server by running `mvn spring-boot:run` at the command line. And in another
terminal window (or tab), we can validate access to the endpoints.
Try curling `localhost:8080/frontend` first. Then switch to your server terminal and
observe the logs:

.log_output_notrace
[source,text]
----
...
2018-02-28 18:25:48.531 2018-02-28 18:25:48,531 [/] INFO  [http-nio-8080-exec-2] m.c.ClientRestController - clientId=null
 30145 --- [nio-8080-exec-2] mcp.cloudtrace.ClientRestController      : clientId=null
...
----

== Adding Trace/Span to the service
Notice that `%TraceId/%SpanId` are not being filled in yet.  Lets fix that by
registering an `org.springframework.web.servlet.HandlerInterceptor` that exhibits
trace instrumentation. It will add the span/trace ids for visibility in loggin.
Use the provided `brave.spring.webmvc.TracingHandlerInterceptor` class for tracing
Spring WEB/MVC/REST endpoints. To configure the interceptor, we will need to customize
MVC using a `org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter` 
(or alternately use `WebMvcConfigurer` when using Spring 5.0 or more).

.TraceServiceOnlyConfiguration
[source,java]
----
public class TraceServiceOnlyConfiguration {
    @Bean
    RestTemplate restTemplate() {
        return new RestTemplate();
    }

    @Bean
    Tracing simpleTracing() {
        return Tracing.newBuilder()
                .currentTraceContext((MDCCurrentTraceContext.create()))
                .build();
    }

    @Bean
    HttpTracing httpTracing(Tracing tracing) {
        return HttpTracing.create(tracing);
    }
	
    @Configuration
    public static class WebTracingConfiguration extends WebMvcConfigurerAdapter {
        private final HttpTracing httpTracing;
        public WebTracingConfiguration(HttpTracing tracing) {
            this.httpTracing = tracing;
        }
        @Override
        public void addInterceptors(InterceptorRegistry registry) {
            registry.addInterceptor(TracingHandlerInterceptor.create(httpTracing));
        }
    }
}
----

The interceptor receives an HttpTracing object which has the job of activating/not a
new trace, and handling any custom trace-scoped needs like propigation, and Trace 
Context commuting.

Because we are using SLF4j - that implements it's own version of Managed Diagnostic Context (MDC). 
Thus, `brave.context.slf4j.MDCCurrentTraceContext` is a ready-made Trace Context that 
will expose current trace and span ID's to SLF4j as logging properties with the given
names: `traceId, spanId, parentId`. If you are using log4j2 instead, then a provided
class `brave.context.log4j2.ThreadContextCurrentTraceContext` will do the same for
log4j2's ThreadContext.

So now, we can restart our service then invoke the `/frontend` and observe 
the output in logs:

.traced_output
[source,text]
----
2018-02-28 18:49:51.200 2018-02-28 18:49:51,200 [6b5e99f057da5abd/1239a4f2e354ecdf] INFO  [http-nio-8080-exec-2] m.c.ClientRestController - clientId=null
 37142 --- [nio-8080-exec-2] mcp.cloudtrace.ClientRestController      : clientId=null
----

== Tracing across service boundaries
Now we can observe trace/span state, but what about request-side tracing?  How can
we commute the 'client-id' header to downstream requests? Logging trace/span is not
enough if we cannot correlate them. To do this, we will add https://github.com/openzipkin/b3-propagation[brave B3-propigation]
(adds X-B3-*Id headers) to HTTP requests made by our `restTemplate` bean.

We continue the code development by modifying our `WebTracingConfiguration` class
to wire up an `HttpTracing` object that will propigate our `client-id` header
across requests in the same trace. The full source to this configuration is in 
`mcp.TracePropagationConfiguration`.  The salient bits are discussed below:

.TracePropagationConfiguration
[source, java]
----
    @Bean
    RestTemplate restTemplate(HttpTracing tracing) {
        return new RestTemplateBuilder()
                .interceptors(TracingClientHttpRequestInterceptor.create(tracing))
                .build();
    }

    @Bean
    Tracing tracing(@Value("${mcp:spring-tracing}") String serviceName) {
        return Tracing
                .newBuilder()
                .sampler(Sampler.ALWAYS_SAMPLE)
                .localServiceName(serviceName)
                .propagationFactory(ExtraFieldPropagation
                        .newFactory(B3Propagation.FACTORY, "client-id"))
                .currentTraceContext(MDCCurrentTraceContext.create())
                .build();
    }
----

By customizing our Tracing bean, we can tell brave that we want our `client-id` header
propated across request/service boundries. Brave provides the `ExtraFieldPropagation` 
class to support comprehensive use of these fields in an application-specific way.  Check the
https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/ExtraFieldPropagation.java[documentation] for further info.

In order to apply tracing concerns to our `restTemplate` we must provide -like the server 
setup- an `org.springframework.http.client.ClientHttpRequestInterceptor` which does the 
client-side tracing work.

.trace_propagated_output
[source,text]
----
2018-03-02 01:13:25.017 2018-03-02 01:13:25,017 [c0d24dc6b7793eb7/738d09ca4e3dd91e]  INFO  [http-nio-8080-exec-2] m.c.ClientRestController - clientId=mario-id
 49687 --- [nio-8080-exec-2] mcp.cloudtrace.ClientRestController      : clientId=mario-id
----

Now, when we call our endpoint, we should see a traceId, spanId, and our `client-id`
as it would have commuted across the entire request chain.

== Shipping traces to somewhere
Usually you will want to send your trace logs to an aggregation server for monitoring.


== Another fork in the road: Sleuth
In the next article, we will solve the same problems using Sleuth - an all-in-One
ready made distribution that binds spring with zipkin tracing properties.


SLF4j 
 1 - Maintain some semblance of inter-process communication 
	 and apply to business Logic.
     HTTP Rest call 
	 	This demo will expose 2 Restful endpoints 
		One will call the other to demonstrate trace propigation across HTTP 
	 Finagle RPC call
	 	This demo will expose 2 finagle services
		"" trace propigation via Finagle (mysql)
	 WebSocket stream
	 	This demo will expose a socket service which receives
		it's stream via kafka
 	
 2 - Apply tracing logic
	- Starting with SLF4j MDC tracing
	- Adds Brave tracing without instrumentation
	- Adds Brave trace with trace shipping to zipkin
	- further trace shipping options

 3 - Stand up tracing aggregator (Brave, Actuator?)
 
 4 - Bring it together using Spring-cloud-sleuth

