= Tracing and Observability with Spring Cloud Sleuth + Grafana
Mario Gray <mgray@pivotal.io>
:Author Initials: MVG
:toc:
:icons:
:numbered:
:website: https://cloud.spring.io/spring-cloud-sleuth/

== Motivation
This example will demonstrate applying tracing capability to an existing
Spring or Spring Boot application.  We will begin by seting up a standard Spring MVC
Restful Json service, and then by adding the necessary pieces for leveraging
trace data and then shiping that to a Zipkin (Brave) server. Ultimately you could
ship to any service, yet this example is simply writing logs, and shipipng metrics
to Zipkin.

To start, you should have an existing application that includes Web, Lombok, and
JPA/H2 for persistence. To follow along with code, visit start.spring.io, or perhaps
download the sourcecode to this example. We will then add some depenencies for enabling
Brave tracing to our services:

.Pom that enables tracing
[source,xml]
----
		<dependency>
			<groupId>io.zipkin.brave</groupId>
			<artifactId>brave</artifactId>
			<version>${brave.version}</version>
		</dependency>
		<dependency>
			<groupId>io.zipkin.reporter2</groupId>
			<artifactId>zipkin-sender-okhttp3</artifactId>
			<version>${zipkin-reporter2.version}</version>
		</dependency>
		<dependency>
			<groupId>io.zipkin.brave</groupId>
			<artifactId>brave-instrumentation-spring-webmvc</artifactId>
			<version>${brave.version}</version>
		</dependency>
		<dependency>
			<groupId>io.zipkin.brave</groupId>
			<artifactId>brave-instrumentation-spring-web</artifactId>
			<version>${brave.version}</version>
		</dependency>
		<!-- slf4j -->
		<dependency>
			<groupId>io.zipkin.brave</groupId>
			<artifactId>brave-context-slf4j</artifactId>
			<version>${brave.version}</version>
		</dependency>        
----

A decription of the pom depenencies here !!!
 * Ship zipkin logs via http calls
 * enable slf4j MDC context propigation (for logging trace/spanc)
 * Adds B3-propigation for commuting trace/spans across HTTP client/service calls.

If you are using log4j, then you'll want to add these artifacts:

.Pom dependencies for log4j2, commons, JUL
[source,xml]
----
		<!-- use log4j2, Commons, or Util-->
		<dependency>
			<groupId>io.zipkin.brave</groupId>
			<artifactId>brave-context-log4j2</artifactId>
			<version>${brave.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-jul</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-jcl</artifactId>
			<version>${log4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j-impl</artifactId>
			<version>${log4j.version}</version>
		</dependency>
----

=== Configuration the Spring application

To get starte
.. trace and span ..



=== What's in the example
Ideation: Expose GET http://reverse 
                -> microservice (reverse.apply)
                    -> microservice (delay.apply)
          Expose POST http://names
                -> microservice (store.apply)
                    -> microservice (delay.apply)
          Expose GET http://names
                -> microservice (get.apply)
                    -> microservice (delay.apply)

            HTTP 400 - Error state on numbers. 
            HTTP 500 - larger than 80 characters 500's the service

Test Suite ( functional ) 

